service_name: config
service: p-config-server
service_plan: trial
parameters:
  git:
    uri: https://github.com/dbbaskette/ESarch-conf
    searchPaths: "{application}"
---
service_name: enginedb
service: cleardb
service_plan: spark
---
service_name: appdb
service: cleardb
service_plan: spark
---
service_name: rabbit
service: cloudamqp
service_plan: lemur
