service_name: enginedb
service: cleardb
service_plan: spark
---
service_name: appdb
service: cleardb
service_plan: spark
---
service_name: rabbit
service: cloudamqp
service_plan: lemur
---
service_name: registry
service: p-service-registry
service_plan: trial