service_name: config
service: p-config-server
service_plan: trial
parameters:
  git:
    uri: https://github.com/dbbaskette/ESarch
    searchPaths: "configuration/{application}"
---
service_name: enginedb
service: cleardb
service_plan: spark
---
service_name: registry
service: p-service-registry
service_plan: trial
---
service_name: rabbit
service: cloudamqp
service_plan: lemur
---
service_name: appdb
service: cleardb
service_plan: spark
---