service_name: config
service: p-config-server
service_plan: trial
parameters:
  git:
    uri: https://github.com/dbbaskette/ESarch
    searchPaths: "configuration/{application}"
---
service_name: enginedb
service: cleardb
service_plan: spark